import os

NAME_CONFIG = 'mareabot.config'
DEFAULT_VALUE = None

# Twitter settings
CONSUMER_KEY = os.getenv('CONSUMER_KEY', DEFAULT_VALUE)
CONSUMER_SECRET=os.getenv('CONSUMER_SECRET', DEFAULT_VALUE)
ACCESS_TOKEN=os.getenv('ACCESS_TOKEN', DEFAULT_VALUE)
ACCESS_TOKEN_SECRET =os.getenv('ACCESS_TOKEN_SECRET', DEFAULT_VALUE)

# Telegram settings
TELEGRAM_TOKEN=os.getenv('TELEGRAM_TOKEN', DEFAULT_VALUE)
TELEGRAM_CHANNEL = os.getenv('TELEGRAM_CHANNEL', DEFAULT_VALUE)
